import 'package:flutter/material.dart';

class Localization {
  static const List<String> _supportedLanguages = ['en', 'ta', 'ml', 'te', 'kn', 'pa', 'mr', 'gu', 'hi'];
  static Locale? _locale;

  static void load(Locale locale) {
    _locale = locale;
  }

  static String translate(String key) {
    final Map<String, Map<String, String>> _localizedValues = {
      'en': {
        'settings_title': 'Settings',
        'profile_settings': 'Profile Settings',
        'my_activity': 'My Activity',
        'earn_with_aiecom': 'Earn with AIEcom',
        'feedback_information': 'Feedback Information',
        'orders': 'Orders',
        'wishlist': 'Wishlist',
        'coupons': 'Coupons',
        'help_center': 'Help Center',
        'aiecom_plus': 'AIEcom Plus',
        'edit_profile': 'Edit Profile',
        'saved_address': 'Saved Address',
        'select_language': 'Select Language',
        'saved_cards': 'Saved Cards',
        'notification_settings': 'Notification Settings',
        'reviews': 'Reviews',
        'questions_answers': 'Questions & Answers',
        'sell_on_aiecom': 'Sell on AIEcom',
        'terms_policies': 'Terms & Policies',
        'browse_faqs': 'Browse FAQs',
      },
      'ta': {
        'settings_title': 'அமைப்புகள்',
        'profile_settings': 'சுயவிவர அமைப்புகள்',
        'my_activity': 'என் செயல்பாடுகள்',
        'earn_with_aiecom': 'AIEcom உடன் சம்பாதிக்க',
        'feedback_information': 'தகவல் மற்றும் கருத்துகள்',
        'orders': 'ஆர்டர்கள்',
        'wishlist': 'விருப்ப பட்டியல்',
        'coupons': 'கூப்பன்கள்',
        'help_center': 'உதவி மையம்',
        'aiecom_plus': 'AIEcom Plus',
        'edit_profile': 'சுயவிவரத்தை மாற்றவும்',
        'saved_address': 'சேமித்த முகவரி',
        'select_language': 'மொழியை தேர்வு செய்யவும்',
        'saved_cards': 'சேமித்த கார்டுகள்',
        'notification_settings': 'அறிக்கைகள் அமைப்புகள்',
        'reviews': 'மதிப்பீடுகள்',
        'questions_answers': 'கேள்விகள் & பதில்கள்',
        'sell_on_aiecom': 'AIEcom இல் விற்க',
        'terms_policies': 'நிபந்தனைகள் மற்றும் கொள்கைகள்',
        'browse_faqs': 'FAQ ஐ உலாவவும்',
      },
      'ml': {
        'settings_title': 'ക്രമീകരണങ്ങൾ',
        'profile_settings': 'പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ',
        'my_activity': 'എന്റെ പ്രവർത്തനം',
        'earn_with_aiecom': 'AIEcom യുമായി വരുമാനം',
        'feedback_information': 'അറിവുകളും അഭിപ്രായങ്ങളും',
        'orders': 'ഓർഡറുകൾ',
        'wishlist': 'ഇച്ഛാപട്ടിക',
        'coupons': 'കൂപണങ്ങൾ',
        'help_center': 'സഹായ കേന്ദ്രം',
        'aiecom_plus': 'AIEcom പ്ലസ്',
        'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
        'saved_address': 'സംരക്ഷിത വിലാസം',
        'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
        'saved_cards': 'സംരക്ഷിത കാർഡുകൾ',
        'notification_settings': 'അറിയിപ്പുകൾ ക്രമീകരണങ്ങൾ',
        'reviews': 'അവലോകനങ്ങൾ',
        'questions_answers': 'ചോദ്യം & മറുപടി',
        'sell_on_aiecom': 'AIEcom ൽ വിൽക്കുക',
        'terms_policies': 'നിയമങ്ങൾ & നയങ്ങൾ',
        'browse_faqs': 'FAQകൾ ബ്രൗസ് ചെയ്യുക',
      },
      'te': {
        'settings_title': 'అమరికలు',
        'profile_settings': 'ప్రొఫైల్ అమరికలు',
        'my_activity': 'నా కార్యకలాపం',
        'earn_with_aiecom': 'AIEcom తో సంపాదించు',
        'feedback_information': 'సమాచారం మరియు అభిప్రాయాలు',
        'orders': 'ఆర్డర్‌లు',
        'wishlist': 'కాంక్షల జాబితా',
        'coupons': 'కూపన్లు',
        'help_center': 'సహాయ కేంద్రం',
        'aiecom_plus': 'AIEcom ప్లస్',
        'edit_profile': 'ప్రొఫైల్ సవరించు',
        'saved_address': 'సురక్షిత చిరునామా',
        'select_language': 'భాషను ఎంచుకోండి',
        'saved_cards': 'సురక్షిత కార్డులు',
        'notification_settings': 'అరిజనాల అమరికలు',
        'reviews': 'సమీక్షలు',
        'questions_answers': 'ప్రశ్నలు & సమాధానాలు',
        'sell_on_aiecom': 'AIEcom లో అమ్ముకోండి',
        'terms_policies': 'నిబంధనలు & విధానాలు',
        'browse_faqs': 'FAQ లను బ్రౌజ్ చేయండి',
      },
      'kn': {
        'settings_title': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
        'profile_settings': 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್ಗಳು',
        'my_activity': 'ನನ್ನ ಚಟುವಟಿಕೆ',
        'earn_with_aiecom': 'AIEcom ಜೊತೆಗೆ ಸಂಪಾದಿಸಿ',
        'feedback_information': 'ಮಾಹಿತಿ ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳು',
        'orders': 'ಆರ್ಡರ್‌ಗಳು',
        'wishlist': 'ಚೆನ್ನಾಗಳ ಪಟ್ಟಿ',
        'coupons': 'ಕೂಪನ್‌ಗಳು',
        'help_center': 'ಸಹಾಯ ಕೇಂದ್ರ',
        'aiecom_plus': 'AIEcom ಪ್ಲಸ್',
        'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
        'saved_address': 'ಉಳಿಸಿದ ವಿಳಾಸ',
        'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
        'saved_cards': 'ಉಳಿಸಿದ ಕಾರ್ಡ್‌ಗಳು',
        'notification_settings': 'ಅರಿವು ಸೆಟ್ಟಿಂಗ್ಗಳು',
        'reviews': 'ಮೌಲ್ಯಮಾಪನಗಳು',
        'questions_answers': 'ಪ್ರಶ್ನೆಗಳು & ಉತ್ತರಗಳು',
        'sell_on_aiecom': 'AIEcom ನಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ',
        'terms_policies': 'ನಿಯಮಗಳು & ನೀತಿಗಳು',
        'browse_faqs': 'FAQ ಗಳನ್ನು ಬ್ರೌಜ್ ಮಾಡಿ',
      },
      'pa': {
        'settings_title': 'ਸੈਟਿੰਗਸ',
        'profile_settings': 'ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਸ',
        'my_activity': 'ਮੇਰੀ ਗਤੀਵਿਧੀ',
        'earn_with_aiecom': 'AIEcom ਨਾਲ ਕਮਾਈ ਕਰੋ',
        'feedback_information': 'ਸੂਚਨਾ ਅਤੇ ਫੀਡਬੈਕ',
        'orders': 'ਆਰਡਰ',
        'wishlist': 'ਇਚਛਾ ਸੂਚੀ',
        'coupons': 'ਕੂਪਨ',
        'help_center': 'ਮਦਦ ਕੇਂਦਰ',
        'aiecom_plus': 'AIEcom ਪਲੱਸ',
        'edit_profile': 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਨ',
        'saved_address': 'ਸੁਰੱਖਿਅਤ ਪਤਾ',
        'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
        'saved_cards': 'ਸੁਰੱਖਿਅਤ ਕਾਰਡ',
        'notification_settings': 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਸੈਟਿੰਗਜ਼',
        'reviews': 'ਸਮੀਖਿਆਵਾਂ',
        'questions_answers': 'ਸਵਾਲ & ਜਵਾਬ',
        'sell_on_aiecom': 'AIEcom ਤੇ ਵੇਚੋ',
        'terms_policies': 'ਸ਼ਰਤਾਂ ਅਤੇ ਨੀਤੀਆਂ',
        'browse_faqs': 'FAQ ਨੂੰ ਬ੍ਰਾਉਜ਼ ਕਰੋ',
      },
      'mr': {
        'settings_title': 'सेटिंग्ज',
        'profile_settings': 'प्रोफाइल सेटिंग्ज',
        'my_activity': 'माझी क्रियाकलाप',
        'earn_with_aiecom': 'AIEcom सह कमवा',
        'feedback_information': 'माहिती आणि अभिप्राय',
        'orders': 'आदेश',
        'wishlist': 'आवडतींची यादी',
        'coupons': 'कूपन',
        'help_center': 'सहाय्य केंद्र',
        'aiecom_plus': 'AIEcom प्लस',
        'edit_profile': 'प्रोफाइल संपादित करा',
        'saved_address': 'जतन केलेला पत्ता',
        'select_language': 'भाषा निवडा',
        'saved_cards': 'जतन केलेले कार्ड',
        'notification_settings': 'सूचना सेटिंग्ज',
        'reviews': 'आढावा',
        'questions_answers': 'प्रश्न & उत्तर',
        'sell_on_aiecom': 'AIEcom वर विकणे',
        'terms_policies': 'अटी आणि धोरणे',
        'browse_faqs': 'FAQ ब्राउझ करा',
      },
      'gu': {
        'settings_title': 'સેટિંગ્સ',
        'profile_settings': 'પ્રોફાઈલ સેટિંગ્સ',
        'my_activity': 'મારી પ્રવૃત્તિ',
        'earn_with_aiecom': 'AIEcom સાથે કમાણી કરો',
        'feedback_information': 'માહિતી અને પ્રતિસાદ',
        'orders': 'ઓર્ડર',
        'wishlist': 'ઇચ્છાઓની યાદી',
        'coupons': 'કૂપન',
        'help_center': 'સહાય કેન્દ્ર',
        'aiecom_plus': 'AIEcom પ્લસ',
        'edit_profile': 'પ્રોફાઈલ સંપાદિત કરો',
        'saved_address': 'સંરક્ષિત સરનામું',
        'select_language': 'ભાષા પસંદ કરો',
        'saved_cards': 'સંરક્ષિત કાર્ડ',
        'notification_settings': 'નોટિફિકેશન સેટિંગ્સ',
        'reviews': 'વિશ્લેષણ',
        'questions_answers': 'સવાલો અને જવાબો',
        'sell_on_aiecom': 'AIEcom પર વેચો',
        'terms_policies': 'શરતો અને નીતિઓ',
        'browse_faqs': 'FAQ બ્રાઉઝ કરો',
      },
      'hi': {
        'settings_title': 'सेटिंग्स',
        'profile_settings': 'प्रोफाइल सेटिंग्स',
        'my_activity': 'मेरी गतिविधि',
        'earn_with_aiecom': 'AIEcom के साथ कमाएँ',
        'feedback_information': 'जानकारी और फीडबैक',
        'orders': 'आदेश',
        'wishlist': 'इच्छा सूची',
        'coupons': 'कूपन',
        'help_center': 'सहायता केंद्र',
        'aiecom_plus': 'AIEcom प्लस',
        'edit_profile': 'प्रोफाइल संपादित करें',
        'saved_address': 'सुरक्षित पता',
        'select_language': 'भाषा चुनें',
        'saved_cards': 'सुरक्षित कार्ड',
        'notification_settings': 'सूचना सेटिंग्स',
        'reviews': 'समीक्षाएँ',
        'questions_answers': 'प्रश्न और उत्तर',
        'sell_on_aiecom': 'AIEcom पर बेचें',
        'terms_policies': 'नियम और नीतियाँ',
        'browse_faqs': 'FAQ ब्राउज़ करें',
      },
    };

    return _localizedValues[_locale?.languageCode]?[key] ?? key;
  }
}
